# Recurring Patterns in Tensorflow

In [46]:
import tensorflow as tf
import numpy as np

## Graph

- Entry points : `tf.placeholder`
- Variables : `tf.get_variable`
- Operations : `tf.add`
- Optimizer : `tf.train.GradientDescentOptimizer(learning_rate)`

## Session

- Session : `tf.Session` or `tf.InteractiveSession`
- Initializer : `tf.global_variables_initializer()`
- Fetch Data : `tf.run([a, b], ... )`; result of operations `a` and `b` are fetched
- Feed Data : `tf.run([...], feed_dict = { x_ : ..., y_ : ... }`; feed data through entry points

## Example : Dummy Graph

Build this graph.

$$
d = a*b + c
$$

- Notice every variable is a scalar
- `a`, `b`, `c` are all placeholders
- `d` is the output of the final operation

In [4]:
tf.reset_default_graph()
a, b, c = (tf.placeholder(dtype=tf.float32,
                          name='{}'.format(name_i)) for name_i in 'abc')
d = (a*b) + c

Check out the operations in the graph

In [6]:
tf.get_default_graph().get_operations()

[<tf.Operation 'a' type=Placeholder>,
 <tf.Operation 'b' type=Placeholder>,
 <tf.Operation 'c' type=Placeholder>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'add' type=Add>]

final output

In [9]:
d

<tf.Tensor 'add:0' shape=<unknown> dtype=float32>

## Execution

In [11]:
sess = tf.InteractiveSession()
d_value = sess.run(d, feed_dict={
    a : 2,
    b : 3,
    c : 4
})
print(d_value)

10.0


## What did we miss?

- Variables : `tf.get_variable`
- Optimizer : `tf.train.GradientDescentOptimizer(learning_rate)`
- Initializer : `tf.global_variables_initializer()`

## Variable

Let us define a new graph, where we have a `tf.Variable` in our graph. 
`Variable` is a special tensor, that maintains it's state in the graph. It is initialized when the 
session begin, by running `tf.global_variables_initializer()`. 

In [33]:
tf.reset_default_graph()
a = tf.placeholder(tf.int64, name='a')
i = tf.get_variable(dtype=tf.int64, name='i', shape=(),
                   initializer=tf.constant_initializer(7))
b = a*i

In [34]:
tf.get_default_graph().get_operations()

[<tf.Operation 'a' type=Placeholder>,
 <tf.Operation 'i/Initializer/Const' type=Const>,
 <tf.Operation 'i' type=VariableV2>,
 <tf.Operation 'i/Assign' type=Assign>,
 <tf.Operation 'i/read' type=Identity>,
 <tf.Operation 'mul' type=Mul>]

## Execute

In [38]:
sess = tf.InteractiveSession()
sess.run(tf.global_variables_initializer())
# see value of i
print('i :', sess.run(i))
for j in range(10):
    # get b
    b_value = sess.run(b, feed_dict= { a : j })
    print('b :', b_value)

i : 7
b : 0
b : 7
b : 14
b : 21
b : 28
b : 35
b : 42
b : 49
b : 56
b : 63


## What did we miss?

- Optimizer : `tf.train.GradientDescentOptimizer(learning_rate)`

*Check out [Linear Regression](Linear%20Regression.ipynb) tutorial.*

## Let's do Matrix Multiplication

In [42]:
tf.reset_default_graph()
A = tf.placeholder(shape=[3,3], dtype=tf.float32, name='A')
B = tf.placeholder(shape=[2,3], dtype=tf.float32, name='B')
C = tf.matmul(A, tf.transpose(B))

In [43]:
C

<tf.Tensor 'MatMul:0' shape=(3, 2) dtype=float32>

## Try out in session

In [52]:
sess = tf.InteractiveSession()
# dummy data
A_value = np.random.randint(0, 5, [3,3])
B_value = np.random.randint(0, 5, [2,3])
C_value = sess.run(C, feed_dict = {
    A : A_value,
    B : B_value
})

In [53]:
print('A\n', A_value)
print('B\n', B_value)
print('C\n', C_value)

A
 [[3 1 2]
 [4 0 0]
 [0 4 2]]
B
 [[4 3 4]
 [0 0 4]]
C
 [[ 23.   8.]
 [ 16.   0.]
 [ 20.   8.]]
